name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main              
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        with:
          commit: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git remote set-url origin https://${{ github.token }}@github.com/${{ github.repository }}

          git fetch origin main
          git rebase origin/main || git rebase --skip

          git add -A
          git commit -m "generated" || echo "No changes"

          git push origin HEAD:refs/heads/main --force-with-lease
